## Mechbot configuration file, enter all required information. ##

Server:
  - "Put Server Here" # Server address
Channel:
  - "Put channel/channels here seperated by commas" # If joining multiple channels do not put any spaces.
Bot_Name:
  - "mechbot" # Pick a name, any name.
Port_Number:
  - 6667 # This is the default port, change to whatever.
